### ISSUE TITLE
Why is "Dresden" listed with 01454?

### ISSUE THREAD

**Issue by m3koenig** [openpotato/openplzapi.website#3]
Hi :)

I do not understand why "Dresden" is listed with "01454"?

![image](https://github.com/openpotato/openplzapi.website/assets/9989457/b453d902-af2b-405f-be1e-e447f26468d0)

```PowerShell
$PostCodeFilter = "01454"
$Page = 1
$Localities = Invoke-WebRequest -UseBasicParsing "https://openplzapi.org/de/Localities?postalCode=$($PostCodeFilter)&pageSize=50&Page=$($Page)" | ConvertFrom-Json
$Localities 
```

I checked the GV100 but I did not find that entry.
Did I something wrong? or why is that the case?

**Comment by fstueber** [comment]
Hi, 

This is an anomaly in the OpenStreetMap (OSM) project. The street "Am Sportplatz" is located in the postcode area 01454 (red line), but at the same time within the municipality Dresden (dotted line). This leads to the entry "Am Sportplatz, 01454 Dresden" in the raw dataset. The error is therefore in OSM and should be corrected there. This is not the first time I have come across such anomalies. Not sure yet how deal with this.

![image](https://github.com/openpotato/openplzapi.website/assets/13050939/06b38449-a688-4838-bf69-6679047e0d25)

**Comment by m3koenig** [comment]
Ahh okay! Thanks!
How did you find this? To lookup the street?

**Comment by fstueber** [comment]
I had a look into the raw data soruces: https://github.com/openpotato/openplzapi.data. There is only one street with 01454 Dresden. This street you can lookup in OSM.
